### ISSUE TITLE
omnimapper died with pcl::OrganizedMultiPlaneSegmentation::segment message

### ISSUE THREAD

**Issue by zikprid0** [CogRob/omnimapper_ros#4]
Hello. I tested omnimapper with docker image cogrob/omnimapper_ros:latest.

Omnimapper died at first cloud callback.

I tested it with ros-dashing, ubuntu bionic, and gazebo simulator.

This is error log of omnimapper.

```
[INFO] [launch]: All log files can be found below /root/.ros/log/2020-04-01-05-57-35-828202-7d859d3941f5-63
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [omnimapper_ros_node-1]: process started with pid [74]
[INFO] [odom_to_base_link-2]: process started with pid [75]
[INFO] [base_link_to_camera_link-3]: process started with pid [76]
[omnimapper_ros_node-1] BoundedPlanePlugin: Constructor.
[omnimapper_ros_node-1] [INFO] [omnimapper_ros_node]: OmniMapperROS: Constructing... Loading ROS Params...
[omnimapper_ros_node-1] [INFO] [omnimapper_ros_node]: Waiting for initial pose from odom to base_link
[omnimapper_ros_node-1] Warning: Invalid frame ID "odom" passed to canTransform argument target_frame - frame does not exist
[omnimapper_ros_node-1]          at line 133 in /tmp/binarydeb/ros-eloquent-tf2-0.12.5/src/buffer_core.cpp
[omnimapper_ros_node-1] [INFO] [omnimapper_ros_node]: GetTransformFunctorTF: waiting for camera_link to base_link to be ready: First attempt.
[omnimapper_ros_node-1] 
[omnimapper_ros_node-1] [INFO] [omnimapper_ros_node]: OmniMapperROS: Installing BoundedPlanePlugin callback.
[omnimapper_ros_node-1] [INFO] [omnimapper_ros_node]: OmniMapperROS: Constructor complete.
[omnimapper_ros_node-1] [INFO] [omnimapper_ros_node]: OmniMapperROS got a cloud.
[omnimapper_ros_node-1] OmniMapperRos: Got cloud from: 1970-Jan-01 00:14:04.691000
[omnimapper_ros_node-1] cloudCallback: conversion took 0.0735939
[omnimapper_ros_node-1] Calling ICP Plugin with stamp: 1970-Jan-01 00:14:04.691000
[omnimapper_ros_node-1] cloudCallback: ofe_cb took 4.76837e-06
[omnimapper_ros_node-1] header time: 1970-Jan-01 00:14:04.691000
[omnimapper_ros_node-1] [pcl::IntegralImageNormalEstimation::setInputCloud] Input dataset is not organized (height = 1).
[omnimapper_ros_node-1] [pcl::IntegralImageNormalEstimation::initCompute] Input dataset is not organized (height = 1).
[omnimapper_ros_node-1] cloudCallback: get_pose took 0.00227904
[omnimapper_ros_node-1] cloudCallback: pub took 0.000308037
[omnimapper_ros_node-1] cloudCallback: cb took: 0.0768781
[omnimapper_ros_node-1] [pcl::OrganizedMultiPlaneSegmentation::segment] Number of points in input cloud (407040) and normal cloud (0) do not match!
```

It seems pcl library could not take normal cloud from input cloud.

This is CloudPoint2 ros message of that test.

```
header:
  stamp:
    sec: 4509
    nanosec: 433000000
  frame_id: camera_lin...
height: 1
width: 407040
fields:
- name: x
  offset: 0
  datatype: 7
  count: 1
- name: y
  offset: 4
  datatype: 7
  count: 1
- name: z
  offset: 8
  datatype: 7
  count: 1
- name: rgb
  offset: 16
  datatype: 7
  count: 1
is_bigendian: false
point_step: 32
row_step: 13025280
data:
- 145
- 224
- 51
- 192
- 68
- 115
- 203
- 191
- 87
- 91
- '...'
is_dense: false
```

I also tested 'is_dense' flag made true by moving robot.

But it was not helpful.
